-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 22:23:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema electronic_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electronic_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electronic_store` DEFAULT CHARACTER SET utf8 ;
USE `electronic_store` ;

-- -----------------------------------------------------
-- Table `electronic_store`.`app_clints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_clints` (
  `ClintId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ClintName` VARCHAR(30) NOT NULL,
  `ClintPhone` VARCHAR(15) NOT NULL,
  `ClintEmail` VARCHAR(30) NOT NULL,
  `ClintAddress` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ClintId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_expenses_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_expenses_categories` (
  `ExpenseId` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ExpenseName` VARCHAR(30) NOT NULL,
  `FixedPayment` DECIMAL(7,0) NOT NULL,
  PRIMARY KEY (`ExpenseId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_users_groups` (
  `GroupId` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `GroupName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`GroupId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_users` (
  `UserId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(12) NOT NULL,
  `Password` CHAR(60) NOT NULL,
  `Email` VARCHAR(40) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL DEFAULT NULL,
  `SubscriptionDate` DATE NOT NULL,
  `LastLogin` DATETIME NOT NULL,
  `GroupId` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `Username` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE,
  INDEX `GroupId` (`GroupId` ASC) VISIBLE,
  CONSTRAINT `app_users_ibfk_1`
    FOREIGN KEY (`GroupId`)
    REFERENCES `electronic_store`.`app_users_groups` (`GroupId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_expenses_daily_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_expenses_daily_list` (
  `DExpensId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ExpenseId` TINYINT(3) UNSIGNED NOT NULL,
  `Payment` DECIMAL(7,0) NOT NULL,
  `Created` DATETIME NOT NULL,
  `UserId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`DExpensId`),
  INDEX `ExpenseId` (`ExpenseId` ASC) VISIBLE,
  INDEX `UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `app_expenses_daily_list_ibfk_1`
    FOREIGN KEY (`ExpenseId`)
    REFERENCES `electronic_store`.`app_expenses_categories` (`ExpenseId`),
  CONSTRAINT `app_expenses_daily_list_ibfk_2`
    FOREIGN KEY (`UserId`)
    REFERENCES `electronic_store`.`app_users` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_notifications` (
  `NotificationId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(30) NOT NULL,
  `Content` VARCHAR(255) NOT NULL,
  `Type` TINYINT(2) NOT NULL,
  `Created` DATETIME NOT NULL,
  `UserID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`NotificationId`),
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `app_notifications_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `electronic_store`.`app_users` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_product_categories` (
  `CatId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CatName` VARCHAR(30) NOT NULL,
  `CatImage` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`CatId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_product_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_product_list` (
  `ProductId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CatId` INT(10) UNSIGNED NOT NULL,
  `ProductName` VARCHAR(30) NOT NULL,
  `ProductImage` VARCHAR(30) NOT NULL,
  `Quntity` INT(10) UNSIGNED NOT NULL,
  `Price` DECIMAL(6,0) UNSIGNED NOT NULL,
  `Barcode` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ProductId`),
  INDEX `CatId` (`CatId` ASC) VISIBLE,
  CONSTRAINT `app_product_list_ibfk_1`
    FOREIGN KEY (`CatId`)
    REFERENCES `electronic_store`.`app_product_categories` (`CatId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_suppliers` (
  `SupplierId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ClintName` VARCHAR(30) NOT NULL,
  `ClintPhone` VARCHAR(15) NOT NULL,
  `ClintEmail` VARCHAR(30) NOT NULL,
  `ClintAddress` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SupplierId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_purchases_invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_purchases_invoices` (
  `InvoiceId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `SupplierId` INT(10) UNSIGNED NOT NULL,
  `PaymentType` TINYINT(1) NOT NULL,
  `PaymentStatus` TINYINT(1) NOT NULL,
  `Created` DATE NOT NULL,
  `Discount` DECIMAL(8,2) NULL DEFAULT NULL,
  `UserId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`InvoiceId`),
  INDEX `UserId` (`UserId` ASC) VISIBLE,
  INDEX `SupplierId` (`SupplierId` ASC) VISIBLE,
  CONSTRAINT `app_purchases_invoices_ibfk_1`
    FOREIGN KEY (`UserId`)
    REFERENCES `electronic_store`.`app_users` (`UserId`),
  CONSTRAINT `app_purchases_invoices_ibfk_2`
    FOREIGN KEY (`SupplierId`)
    REFERENCES `electronic_store`.`app_suppliers` (`SupplierId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_purchases_invoices_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_purchases_invoices_details` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProductId` INT(10) UNSIGNED NOT NULL,
  `Quantity` SMALLINT(6) NOT NULL,
  `ProductPrice` DECIMAL(7,2) NOT NULL,
  `InvoiceId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `ProductId` (`ProductId` ASC) VISIBLE,
  INDEX `InvoiceId` (`InvoiceId` ASC) VISIBLE,
  CONSTRAINT `app_purchases_invoices_details_ibfk_1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `electronic_store`.`app_product_list` (`ProductId`),
  CONSTRAINT `app_purchases_invoices_details_ibfk_2`
    FOREIGN KEY (`InvoiceId`)
    REFERENCES `electronic_store`.`app_purchases_invoices` (`InvoiceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_purchases_invoices_receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_purchases_invoices_receipts` (
  `ReceiptId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `InvoiceId` INT(10) UNSIGNED NOT NULL,
  `PaymentType` TINYINT(1) NOT NULL,
  `PaymentAmount` DECIMAL(8,2) NOT NULL,
  `PaymentLiteral` VARCHAR(60) NOT NULL,
  `BankName` VARCHAR(30) NULL DEFAULT NULL,
  `BankAccountNumber` VARCHAR(30) NULL DEFAULT NULL,
  `CheckNumber` VARCHAR(15) NULL DEFAULT NULL,
  `TransferedTo` VARCHAR(30) NULL DEFAULT NULL,
  `Created` DATE NOT NULL,
  `UserId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ReceiptId`),
  INDEX `InvoiceId` (`InvoiceId` ASC) VISIBLE,
  INDEX `UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `app_purchases_invoices_receipts_ibfk_1`
    FOREIGN KEY (`InvoiceId`)
    REFERENCES `electronic_store`.`app_purchases_invoices` (`InvoiceId`),
  CONSTRAINT `app_purchases_invoices_receipts_ibfk_2`
    FOREIGN KEY (`UserId`)
    REFERENCES `electronic_store`.`app_users` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_sales_invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_sales_invoices` (
  `InvoiceId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ClintId` INT(10) UNSIGNED NOT NULL,
  `PaymentType` TINYINT(1) NOT NULL,
  `PaymentStatus` TINYINT(1) NOT NULL,
  `Created` DATE NOT NULL,
  `Discount` DECIMAL(8,2) NULL DEFAULT NULL,
  `UserId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`InvoiceId`),
  INDEX `UserId` (`UserId` ASC) VISIBLE,
  INDEX `ClintId` (`ClintId` ASC) VISIBLE,
  CONSTRAINT `app_sales_invoices_ibfk_1`
    FOREIGN KEY (`UserId`)
    REFERENCES `electronic_store`.`app_users` (`UserId`),
  CONSTRAINT `app_sales_invoices_ibfk_2`
    FOREIGN KEY (`ClintId`)
    REFERENCES `electronic_store`.`app_clints` (`ClintId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_sales_invoices_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_sales_invoices_details` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProductId` INT(10) UNSIGNED NOT NULL,
  `Quantity` SMALLINT(6) NOT NULL,
  `ProductPrice` DECIMAL(7,2) NOT NULL,
  `InvoiceId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `ProductId` (`ProductId` ASC) VISIBLE,
  INDEX `InvoiceId` (`InvoiceId` ASC) VISIBLE,
  CONSTRAINT `app_sales_invoices_details_ibfk_1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `electronic_store`.`app_product_list` (`ProductId`),
  CONSTRAINT `app_sales_invoices_details_ibfk_2`
    FOREIGN KEY (`InvoiceId`)
    REFERENCES `electronic_store`.`app_sales_invoices` (`InvoiceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_sales_invoices_receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_sales_invoices_receipts` (
  `ReceiptId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `InvoiceId` INT(10) UNSIGNED NOT NULL,
  `PaymentType` TINYINT(1) NOT NULL,
  `PaymentAmount` DECIMAL(8,2) NOT NULL,
  `PaymentLiteral` VARCHAR(60) NOT NULL,
  `BankName` VARCHAR(30) NULL DEFAULT NULL,
  `BankAccountNumber` VARCHAR(30) NULL DEFAULT NULL,
  `CheckNumber` VARCHAR(15) NULL DEFAULT NULL,
  `TransferedTo` VARCHAR(30) NULL DEFAULT NULL,
  `Created` DATE NOT NULL,
  `UserId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ReceiptId`),
  INDEX `InvoiceId` (`InvoiceId` ASC) VISIBLE,
  INDEX `UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `app_sales_invoices_receipts_ibfk_1`
    FOREIGN KEY (`InvoiceId`)
    REFERENCES `electronic_store`.`app_sales_invoices` (`InvoiceId`),
  CONSTRAINT `app_sales_invoices_receipts_ibfk_2`
    FOREIGN KEY (`UserId`)
    REFERENCES `electronic_store`.`app_users` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_users_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_users_privileges` (
  `PrivilegeId` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Privilege` VARCHAR(30) NOT NULL,
  `PrivilegeTitle` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`PrivilegeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_users_groups_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_users_groups_privileges` (
  `Id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `GroupId` TINYINT(1) UNSIGNED NOT NULL,
  `PrivilegeId` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `GroupId` (`GroupId` ASC) VISIBLE,
  INDEX `PrivilegeId` (`PrivilegeId` ASC) VISIBLE,
  CONSTRAINT `app_users_groups_privileges_ibfk_1`
    FOREIGN KEY (`GroupId`)
    REFERENCES `electronic_store`.`app_users_groups` (`GroupId`),
  CONSTRAINT `app_users_groups_privileges_ibfk_2`
    FOREIGN KEY (`PrivilegeId`)
    REFERENCES `electronic_store`.`app_users_privileges` (`PrivilegeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electronic_store`.`app_users_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronic_store`.`app_users_profiles` (
  `UserId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(10) NOT NULL,
  `LastName` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(50) NULL DEFAULT NULL,
  `DateOfBirth` DATE NULL DEFAULT NULL,
  `Avatar` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `app_users_profiles_ibfk_1`
    FOREIGN KEY (`UserId`)
    REFERENCES `electronic_store`.`app_users` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
